### ISSUE TITLE
Server crashes on attempt to reconnect

### ISSUE THREAD

**Issue by matthew-ia** [TeamSunergy/chase-ui#6]
This happens if `server-test.py` is stopped and then started again.

```
Listening on port:  4001
[2018-06-15T15:07:20.046] [INFO] chase-server - Connection made with host: 127.0.0.1 on port: 25000
[2018-06-15T15:07:24.295] [INFO] chase-server - Event: SocketIO Connection Established w/ browser
[2018-06-15T15:08:16.482] [INFO] chase-server - Socket closed - Attempting to establish a connection
[2018-06-15T15:08:26.486] [INFO] chase-server - Connection made with host: 127.0.0.1 on port: 25000
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (_stream_writable.js:193:12)
    at Parser.Writable.write (_stream_writable.js:240:5)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)
```

**Comment by stevesoaress** [comment]
Shifting my focus to look at this item. I will also work on the monitoring back-end that sends notifications.

**Comment by stevesoaress** [comment]
Working on implementing functionality w/ rabbitmq

**Comment by stevesoaress** [comment]
Closing this issue. With the adoption of RabbitMQ, this shouldn't be a problem.
